#!/usr/bin/env python
# coding: utf-8

import re
import sys
reload(sys)
sys.setdefaultencoding('utf-8')
import polib
import io

version='1.0.0'


sve_file=sys.argv[1]
po_file=sys.argv[2]
#sve_enc=sys.argv[3]

po = polib.POFile(wrapwidth=999999)
po.metadata = {
  'Project-Id-Version': 'PACKAGE VERSION',
  'Report-Msgid-Bugs-To': '',
  'POT-Creation-Date': '1970-1-01 00:00+0000',
  'PO-Revision-Date': 'YEAR-MO-DA HO:MI+ZONE',
  'Last-Translator': 'FULL NAME <EMAIL@ADDRESS>',
  'Language-Team': 'LANGUAGE <LL@li.org>',
  'Language': '',
  'MIME-Version': '1.0',
  'Content-Type': 'text/plain; charset=UTF-8',
  'Content-Transfer-Encoding': '8bit',
  'X-Generator': 'sve2po v.{}'.format(version),
}

sve_text = io.open(sve_file, 'r', encoding='utf-8').read()
sve_pattern = "(\d+):(.*)"
sve_entries = re.findall(sve_pattern, sve_text)
entry_added = 0

for t in sve_entries:
  t_seq = t[0]
  t_str = t[1]
  if t_str == '':
    print "WARN: {} - empty entry at {}. Skipping".format(sve_file,t_seq)
    continue
  current_entries = [e for e in po]
  for entry in current_entries:
    entry_added = 0
    print entry.msgid
    if entry.msgid == t_str:
      print "dupe found"
      entry.occurrences.append((sve_file, t_seq))
      entry_added = 1
      break
  if entry_added == 0:
    entry = polib.POEntry(
      msgid=t_str,
      msgstr='',
      occurrences=[(sve_file, t_seq),]
    )
    po.append(entry)

po.save(po_file)
