#!/usr/bin/env python
# coding: utf-8

import re
import sys
reload(sys)
sys.setdefaultencoding('utf-8')
import polib
import io
import argparse

version='1.0.0'

parser = argparse.ArgumentParser(description='Convert indexed TXT files to gettext PO',formatter_class=argparse.ArgumentDefaultsHelpFormatter)
parser.add_argument('-i', dest='input_file', help='input file', required=True)
parser.add_argument('-o', dest='output_file', help='output file')
parser.add_argument('--encoding', dest='enc', default='utf-8', help='source encoding')
args=parser.parse_args()

#init vars
input_file=args.input_file
output_file=args.output_file
enc=args.enc

po = polib.POFile(wrapwidth=999999)
po.metadata = {
  'Project-Id-Version': 'PACKAGE VERSION',
  'Report-Msgid-Bugs-To': '',
  'POT-Creation-Date': '1970-1-01 00:00+0000',
  'PO-Revision-Date': 'YEAR-MO-DA HO:MI+ZONE',
  'Last-Translator': 'FULL NAME <EMAIL@ADDRESS>',
  'Language-Team': 'LANGUAGE <LL@li.org>',
  'Language': '',
  'MIME-Version': '1.0',
  'Content-Type': 'text/plain; charset=UTF-8',
  'Content-Transfer-Encoding': '8bit',
  'X-Generator': 'indexed_txt2po v.{}'.format(version),
}

text = io.open(input_file, 'r', encoding='utf-8').read()
pattern = "(\d+):(.*)"
entries = re.findall(pattern, text)
entry_added = 0

for t in entries:
  t_seq = t[0]
  t_str = t[1]
  if t_str == '':
    print "WARN: {} - empty entry at {}. Skipping".format(input_file,t_seq)
    continue
  current_entries = [e for e in po]
  for entry in current_entries:
    entry_added = 0
    print entry.msgid
    if entry.msgid == t_str:
      print "dupe found"
      entry.occurrences.append((input_file, t_seq))
      entry_added = 1
      break
  if entry_added == 0:
    entry = polib.POEntry(
      msgid=t_str,
      msgstr='',
      occurrences=[(input_file, t_seq),]
    )
    po.append(entry)

po.save(output_file)
