#!/usr/bin/env python
# coding: utf-8

version='1.0.0'

import argparse
import bgforge_po
import polib

parser = argparse.ArgumentParser(description='Load Fallout MSG into gettext PO msgstr',formatter_class=argparse.ArgumentDefaultsHelpFormatter)
parser.add_argument('-i', dest='input_file', help='input MSG file', required=True)
parser.add_argument('-o', dest='output_file', help='output PO file', required=True)
parser.add_argument('--path', dest='path', help='load as filename (PO occurence). If not specified, defaults to input filename')
parser.add_argument('-e','--encoding', dest='encoding', default='cp1252', help='source encoding')
parser.add_argument('-w','--width', dest='width', default='78', help='output PO wrapwith')
args=parser.parse_args()

input_file = args.input_file
output_file = args.output_file
if args.path == None:
  path = args.input_file
else:
  path = args.path
encoding = args.encoding
width = int(args.width)

po = polib.pofile(output_file, wrapwidth=width)
po.metadata = bgforge_po.metadata
po = bgforge_po.file2msgstr(input_file, po, path, encoding=encoding, width=width)
po.save(output_file)
