#!/usr/bin/env python
# coding: utf-8

version='1.0.0'

import argparse
import bgforge_po

parser = argparse.ArgumentParser(description='Extract indexed TXT from gettext PO',formatter_class=argparse.ArgumentDefaultsHelpFormatter)
parser.add_argument('-i', dest='input_file', help='input PO file', required=True)
parser.add_argument('-o', dest='output_file', help='output SVE file', required=True)
parser.add_argument('-e', '--encoding', dest='encoding', help='output encoding',default='cp1252')
parser.add_argument('--path', dest='path', help='occurrence in PO (relative path) - defaults to output TXT/SVE name')
args=parser.parse_args()

if args.path == None:
  path = output_file
else:
  path = args.path

bgforge_po.po2file(args.input_file,args.output_file,args.encoding,path)
