#!/usr/bin/env python
# coding: utf-8

version='1.0.0'

import argparse
import bgforge_po

parser = argparse.ArgumentParser(description='Extract indexed TXT from gettext PO',formatter_class=argparse.ArgumentDefaultsHelpFormatter)
parser.add_argument('-i', dest='input_file', help='input file', required=True)
parser.add_argument('-o', dest='output_file', help='output file')
parser.add_argument('-e', '--encoding', dest='encoding', help='output encoding',default='cp1252')
parser.add_argument('--extract-file', dest='extract_file', help='filename to extract, as recorded in PO')
args=parser.parse_args()

if args.extract_file == None:
  extract_file = output_file
else:
  extract_file = args.extract_file

bgforge_po.po2file(args.input_file,args.output_file,args.encoding,extract_file)
