#!/usr/bin/env python
# coding: utf-8

version='1.0.0'

import io
import os
import argparse
import sys
import polib
import shutil
import re
import os
import bgforge_po

valid_extensions = bgforge_po.valid_extensions
default_poify_dir = bgforge_po.get_poify_dir()

#parse args
parser = argparse.ArgumentParser(description='Poify files in selected directory',formatter_class=argparse.ArgumentDefaultsHelpFormatter)
parser.add_argument('DIR', nargs = '?', default = default_poify_dir, help='source language directory (default: ./english)')
parser.add_argument('-e', dest='enc', help='source encoding', default='cp1252')
parser.add_argument('--no-lowercase', dest='nolowercase', default=False, action='store_true', help="don't lowercase filenames before poifying")
parser.add_argument('-w', dest='width', default='78', help='output PO wrapwith')
args=parser.parse_args()


#init vars
poify_dir = args.DIR
bgforge_po.dir_or_exit(poify_dir)
enc = bgforge_po.get_enc(args.DIR)
nolowercase = args.nolowercase
width = int(args.width)

devnull = open(os.devnull, 'w')

#prepare po dir
def prepare_po_dir(d):
  if not os.path.isdir(d):
    shutil.rmtree(d,ignore_errors=True)
    os.makedirs(d)
  tmp_dir = d + '/tmp'
  if not os.path.isdir(tmp_dir):
    shutil.rmtree(tmp_dir,ignore_errors=True)
    os.makedirs(tmp_dir)

def clean_po_dir(d):
  tmp_dir = d + '/tmp'
  shutil.rmtree(tmp_dir,ignore_errors=True)

def poify(dir): #relative path
  po_dir = bgforge_po.po_dirname
  prepare_po_dir(po_dir)
  #process with po_tool
  with bgforge_po.cd(dir):
    #Final PO
    lang = bgforge_po.basename(dir)
    dst_file = po_dir + '/' + lang + '.pot'
    po = polib.POFile(wrapwidth=width)
    po.metadata = bgforge_po.metadata

    for dir_name, subdir_list, file_list in sorted(os.walk('.',topdown=False)):
      subdir_list.sort()
      file_list.sort()
      for file_name in file_list:
        full_name=os.path.join(dir_name, file_name)
        full_name=re.sub('^\./','',full_name)  #remove trailing './'
        ext=bgforge_po.get_ext(file_name)
        if ext in valid_extensions:
            po_tool=ext + '2po'
        else:
          continue

        #checked txt is indexed and if it is, process it
        if ext == 'txt':
          if bgforge_po.check_indexed(full_name):
            print "{} is indexed TXT".format(full_name)
          else:
            print "{} is TXT, but not indexed. Skipping!".format(full_name)
            continue

        print "processing {}".format(full_name)
        po2 = bgforge_po.file2po2(full_name)
        for e2 in po2:
          po.append(e2)
  po = bgforge_po.po_make_unique(po)
  po.save(dst_file)

  clean_po_dir(po_dir)
  print "Processed directory {} with encoding {}, the result is in {}/{}/{}.pot".format(poify_dir,enc,tra_dir,po_dir,lang)

tra_dir = os.path.relpath(bgforge_po.parent_dir(poify_dir))

#lowercase if not disabled on cmd
if nolowercase == False:
  bgforge_po.lowercase_recursively(tra_dir)

with bgforge_po.cd(bgforge_po.parent_dir(os.path.abspath(poify_dir))):
  poify(bgforge_po.basename(poify_dir)) #keeping relative occurences in resulting po
