#!/usr/bin/env python
# coding: utf-8

version='1.0.0'

import argparse
import polib
import bgforge_po

parser = argparse.ArgumentParser(description='Resave PO file using polib API, to correct formatting',formatter_class=argparse.ArgumentDefaultsHelpFormatter)
parser.add_argument('INPUT_FILE', help='PO file to resave')
args=parser.parse_args()

po = polib.pofile(args.INPUT_FILE)
po.save(args.INPUT_FILE)
bgforge_po.clean_female_csv(args.INPUT_FILE)
