#!/usr/bin/env python
# coding: utf-8

import re
import sys
reload(sys)
sys.setdefaultencoding('utf-8')
import polib
import io

version='1.0.0'


sve_file=sys.argv[1]
po_file=sys.argv[2]
sve_enc=sys.argv[3]

po = polib.POFile(wrapwidth=999999)
po.metadata = {
  'Project-Id-Version': 'PACKAGE VERSION',
  'Report-Msgid-Bugs-To': '',
  'POT-Creation-Date': '1970-1-01 00:00+0000',
  'PO-Revision-Date': 'YEAR-MO-DA HO:MI+ZONE',
  'Last-Translator': 'FULL NAME <EMAIL@ADDRESS>',
  'Language-Team': 'LANGUAGE <LL@li.org>',
  'Language': '',
  'MIME-Version': '1.0',
  'Content-Type': 'text/plain; charset=UTF-8',
  'Content-Transfer-Encoding': '8bit',
  'X-Generator': 'sve2po v.{}'.format(version),
}

sve_text = io.open(sve_file, 'r', encoding=sve_enc).read()
sve_pattern = "(\d+):(.*)"
sve_entries = re.findall(sve_pattern, sve_text)

for t in sve_entries:
  t_seq = t[0]
  t_str = t[1]
  if t_str == '':
    print "WARN: {} - empty entry at {}. Skipping".format(sve_file,t_seq)
    continue
  t_str_u = unicode(t_str)
  entry = polib.POEntry(
    msgid=t_str_u,
    msgstr='',
    occurrences=[(sve_file, t_seq),]
  )
  po.append(entry)

po.save(po_file)
