name: "Lint"

on:
  pull_request:
  push:

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: ShellCheck
        uses: ludeeus/action-shellcheck@master

      - name: Ruff
        uses: astral-sh/ruff-action@v3

      - name: Ruff format
        uses: astral-sh/ruff-action@v3
        with:
          args: "format --check"

      - uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: ty check
        run: uv run ty check
