name: "Lint"

on:
  pull_request:
  push:

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: ShellCheck
        uses: ludeeus/action-shellcheck@master

      - name: Ruff
        uses: astral-sh/ruff-action@v3

      - name: Ruff format
        uses: astral-sh/ruff-action@v3
        with:
          args: "format --check"
